baseurl = "https://www.straitsproperty.com/"
title = "Straits Property"
languageCode = "en-us"

# Theme to use
theme = "simple-hugo-theme"

# Pagination
paginate = 10
paginatePath = "page"

# Google analytics
# googleAnalytics = ""

# Copyright
copyright = "© 2019 straitsproperty.com"

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header

  [[menu.main]]
    url = "/about/"
    name = "about ian"
    weight = 1
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 2

  # Footer
  [[menu.footer]]
    url = "/posts/index.xml"
    name = "rss feed"
    weight = 1



# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"
